# This is a basic workflow to help you get started with Actions

name: CI

env:
  CONFLUENCE_USERNAME: ${{ secrets.CONFLUENCE_USERNAME }}
  CONFLUENCE_PASSWORD: ${{ secrets.CONFLUENCE_PASSWORD }}
  CONFLUENCE_ENDPOINT: "https://uniopgaver.atlassian.net/rest/api"

on: [pull_request]
jobs:
  publish_confluence:
    runs-on: ubuntu-latest
    name: Publish docs to confluence
    steps:
      - uses: actions/checkout@v1
      - name: Generate site.yaml
        uses: simasbu/confluence-page-creator-action@main
        with:
          token: ${{ secrets.GIT_TOKEN }}
          directory: "confluence"
          parentPageTitle: "Delivery and Service Management Home"
          spaceKey: "UNIOPGAVER"

      - name: Publish
        run: mvn confluence-reporting:deploy -Dconfluence.endPoint=$CONFLUENCE_UENDPOINT -Dconfluence.userName=$CONFLUENCE_USERNAME -Dconfluence.password=$CONFLUENCE_PASSWORD -Dconfluence.childrenTitlesPrefixed=false
