# This is a basic workflow to help you get started with Actions

name: CI

on: [pull_request]
jobs:
  publish_confluence:
    runs-on: ubuntu-latest
    name: Publish docs to confluence
    steps:
      - uses: actions/checkout@v1
      - name: publish to confluence
        uses: simasbu/confluence-page-creator-action@main
        with:
          token: ${{ secrets.GIT_TOKEN }}
          directory: "confluence"
          parentPageTitle: "Delivery and Service Management Home"
