# This is a basic workflow to help you get started with Actions

name: CI

env:
  CONFLUENCE_USERNAME: ${{ secrets.CONFLUENCE_USERNAME }}
  CONFLUENCE_PASSWORD: ${{ secrets.CONFLUENCE_PASSWORD }}
  CONFLUENCE_ENDPOINT: "https://confluence.build.ingka.ikea.com/rest/api"

on: [pull_request]
jobs:
  publish_confluence:
    runs-on: ubuntu-latest
    name: Publish docs to confluence
    steps:
      - uses: actions/checkout@v1
      - name: Generate site.yaml
        uses: simasbu/confluence-site-descriptor-action@main
        with:
          localDirectory: "confluence"
          parentPageTitle: "Test"
          homePageTitle: "Test_product_1"
          spaceKey: "DSM"

      # Maven package
      - name: Setup JDK
        uses: actions/setup-java@v1
        with:
          java-version: 13

      - name: Publish
        run: mvn confluence-reporting:deploy -Dconfluence.endPoint=$CONFLUENCE_ENDPOINT -Dconfluence.userName=$CONFLUENCE_USERNAME -Dconfluence.password=$CONFLUENCE_PASSWORD -Dconfluence.childrenTitlesPrefixed=false
